name: publish



on: [push]
  


jobs:
  publish-hello-docker-image:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Login to GitHub Container Registry
        uses: actions/checkout@v2

      - name: Build the hello-docker Docker image
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_IMG_PASS }}
          run: |
                 docker build . --tag ghcr.io/deselikem/hello-docker-gcr-demo:latest
                 docker run ghcr.io/deselikem/hello-docker-gcr-demo:latest
                 docker push ghcr.io/deselikem/hello-docker-gcr-demo:latest

      
